name: Build and test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install Dependencies
        run: yarn install
      - name: Lint the Project
        run: yarn lint
      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile  # Use the Dockerfile in the root of the repository
          push: false  # Do not push the image to Docker Hub
          tags: alexandrastalmans/webapp:latest
